baseURL = 'https://joe.lothan.net/'
languageCode = 'en-us'
title = 'Joe Lothan'
theme = ['hugo-video', 'hermit']

[author]
	name = "Joe Lothan"

[params]
    customCSS       = ["css/custom.css"]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

	[[params.social]]
		name = "github"
		url = "https://github.com/ert-plus"

    [[params.social]]
		name = "twitter"
		url = "https://twitter.com/ert_plus"



[menu]
#    maybe some day...
#    [[menu.main]]
#        name = "Blog"
#        url = "blog/"

    [[menu.main]]
        name = "CTFs"
        url = "ctfs/"